/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare class BaalsClient {
  constructor(dataDir: string, backend?: string | undefined | null)
  start(): void
  stop(): void
  chainStateJson(): string
  getBlockByHeight(height: number): string | null
  getTransaction(hashHex: string): string | null
  getAccount(pubkeyHex: string): string | null
  submitTx(txJson: string): void
  createAccount(pubkeyHex: string, balance: number): void
  addPeer(address: string): void
  removePeer(address: string): void
  knownPeers(): Array<string>
  triggerSync(): void
}
